version: '3.8'
services:
 mosquitto:
   image: eclipse-mosquitto:2.0
   ports:
     - "1883:1883"
     - "9001:9001"
   volumes:
     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
   restart: unless-stopped
 sensor:
   build: .
   command: python src/devices/virtual_sensor.py
   volumes:
     - .:/iot-project
   working_dir: /iot-project
   depends_on:
     - mosquitto
   restart: unless-stopped